- title: 'Signature Massage'
  description: 'The Symphony Signature Massage is a uniquely stylized composition
    of body work. We choreograph a massage using a variety of hands on techniques
    along with select instruments to make sure each part of your body is given the
    exact attention it needs.'

- title: 'Facial life and Drainage'
  description: 'A very gentle but highly effective way to drain excess fluid from
    the face. Lymphatic Drainage is done with MediCupping techniques using Phytomer
    products. This will not leave marks on your face and is also offered in a series
    of services for best results. The 60-minute session includes a neck, shoulder
    and scalp massage.'

- title: 'Prenatal Massage'
  description: 'Pregnacy is an amazing time for a Mom-to-be but it comes along with
    a whole new set of aches and pains.  From shoulders to ankles, every part of the
    body goes through changes to accomodate new life.  We use Phytomer Seatonic Firming
    Oil as it is proven to be safe during pregnancy and effective in reducing stretch
    marks. '

- title: 'Body Contouring'
  description: This is mostly a MediCupping service. Cups are used for Lymphatic Drainage
    and to release restricted facia. Phytomer products are used to help promote the
    circulation of lymph and reduce solid bloat. The best results are seen when done
    in a series of 10, 2-3 times a year as every person is different. Regular massage
    will support your results between each series. You take home a silicon cup and
    products for home upkeep. Fantastic results are seen when nutrition and exercise
    are a part of the plan.
      
- title: 'Phytomer Self-Heating Mud Pack'
  description: Our Phytomer Self Heating Mud wrap is a luxurious detoxification treatment
    like no other. This unique and exclusive thermal marine mud helps relieve congestion
    and nourish the tissue. Once mixed with room temperature water the mud gently
    begins to heat up, simultaneously soothing the nerves and muscles. As the heat
    increases, so does the activity of the product, with millions of little bubbles
    performing a micro-massage helping to absorb every trace of tension, and improve
    tissue function.  $10 per additional area, inquire regarding areas

- title: 'Fusion FX Percussion Session'
  description: 'Keep your clothes on! We use a Fusion FX Massage Tool and focus on
    a specific soft tissue issue. The percussive action can help relieve taut, overused
    muscles in an almost chaotic way. There are multiple speeds and attachments including
    a heated attachment for more stubborn muscles.'

- title: 'Stretch-Ahhhhh'
  description: 'Exercising a lot and not stretching enough?  Your Therapist can help
    you maintain your top level with stretching techniques and specific balms formulated
    for flexability'
